GET  http://localhost:3000/api/genres 
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ3YjM5MGU0Yzk1YmRmMzNjMTg1MjAiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2OTkxOTk0OTB9.9YktSyPZjKsUZHzgCoVefrjWmeBcBymC3gX2NDMj458

# {
# 	"name": "Tella"
# }

# {
#     "email": "boluwatifetella2@gmail.com",
# 	"name": "Tella Boluwatife",
#     "password": "password"
# }

